### ISSUE TITLE
Create the default vehicle collection

### ISSUE THREAD

**Issue by saitoshi** [shocking-development/shockingdevelopment#11]
Please do work for this task in a branch named issue-#11.

**Comment by CalianaFortin** [comment]
### **Overview**
For this review, we're going to take a look at the Landing Page.

### **Review Branch**
review-#11

### **Files to review**
[settings.development.json](https://github.com/shocking-development/shockingdevelopment/blob/issue-%2311/config/settings.development.json)
[Cars.js](https://github.com/shocking-development/shockingdevelopment/blob/issue-%2311/app/imports/api/cars/Cars.js)

### **Checklists**

[Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
[Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
[JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)

### **Due date**
Monday, February 8
