### ISSUE TITLE
Review: List Profile Admin Page

### ISSUE THREAD

**Issue by kyraikeda** [shocking-development/shockingdevelopment#121]
## Overview

Please work on reviewing the List Profile Admin page.

## Files to review

* [ListProfileAdmin.jsx](https://github.com/shocking-development/shockingdevelopment/blob/master/app/imports/ui/pages/profile/ListProfileAdmin.jsx)
* [ProfileItemAdmin.jsx](https://github.com/shocking-development/shockingdevelopment/blob/master/app/imports/ui/components/profile/ProfileItemAdmin.jsx)
## Checklists

* [Architecture](../tree/master/checklists/architecture-checklist.md)
* [Design](../tree/master/checklists/design-checklist.md)
* [JS](../tree/master/checklists/js-checklist.md)
* [Meteor](../tree/master/checklists/meteor-checklist.md)
* [React](../tree/master/checklists/react-checklist.md)
* [Testing](../tree/master/checklists/testing-checklist.md)

## Due date

Please work on this before class on Tuesday 4/11. 

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by saitoshi** [comment]
### Design-05: Ensure comments are appropriate.
For line 95, 103 make sure that the comments do not say Stuff. Rather it should say UserInfo collection since it is getting access from there.
### Design-09: Ensure reusable code is exported or made available in the appropriate place.
For the table headers, since the first letters of the each words are capitalize so should the other headers.

Besides those two I personally cannot see anything else.

**Comment by kyraikeda** [comment]
### Design-05: Ensure comments are appropriate.
Lines 9, 96, and 104 do not accurately describe the code.
Should use /* instead of /** for comments like in lines 12 and 20.

**Comment by trey-sumida** [comment]
ProfileItemAdmin.jsx:
Design-05: Ensure comments are appropriate.
Comments on line 7 refers to "Stuff" 
JS-08: Use JSDoc comments appropriately.
Comments use JSDoc but should probably use /*
Consider converting to a react functional components as there is no state being used

**Comment by jtmoka** [comment]
I Can not find any violations of the checklist in this page. Every thing looks good.

**Comment by mkirts** [comment]
ProfileItemAdmin.jsx
Design-05: Ensure comments are appropriate
Line 7 comment refers to the "Stuff" files, and should be renamed or removed

Other than that, there was no noticeable violations with the code.

**Comment by christianjensenv** [comment]
ProfileItemAdmin.jsx

**Design-05: Ensure comments are appropriate.**
L7 comment need to describe the code better. Currently describes it as stuff. 

**JS-08: Use JSDoc comments appropriately.**
JSDoc comments used incorrectly, use /*.....*/ instead.

**Comment by CalianaFortin** [comment]
ProfileItemAdmin.jsx:

**Design-05: Ensure comments are appropriate.**
line 7 refers to "_Stuff_".

**Comment by alohajerome** [comment]
ProfileItemAdmin.jsx:
-Design-05: Ensure comments are appropriate 
Some comments are not related to the actual code
ListProfileAdmin.jsx:
-The Same thing... Design-05: Ensure comments are appropriate
Line 95 comments refers to “Stuff” Which is completely different from the actual code

**Comment by cammoore** [comment]
## ListProfileAdmin.jsx

JS-08 Prefer // to /**.

L52 - 60 may want to consider extracting styles to a common place. Or
declaring some style consts.

REACT-06 L106: use a const.

## ProfileItemAdmin.jsx

REACT-09 L8 Prefer functions.
