### ISSUE TITLE
Review: Landing Page

### ISSUE THREAD

**Issue by CalianaFortin** [shocking-development/shockingdevelopment#19]
## Overview

For this review, we're going to take a look at the Landing Page.

## Review Branch

review-#5

## Files to review

* [LandingAddition.jsx](https://github.com/shocking-development/shockingdevelopment/blob/issue-%235/app/imports/ui/components/LandingAddition.jsx)
* [Landing.jsx](https://github.com/shocking-development/shockingdevelopment/blob/issue-%235/app/imports/ui/pages/Landing.jsx)

## Checklists

(Please edit the following list if necessary to indicate the actual checklists to be used.)

* [Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)

## Due date

Tuesday, February 9

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by trey-sumida** [comment]
Design-07: Ensure code is readable
Landing.jsx:
Consider putting comments to describe what information each column has

Design-08: Ensure code is DRY
Landing.jsx:
Styling is repeated for multiple components, consider putting it in the css file and giving the components a className

**Comment by kyraikeda** [comment]
### LandingAddition.jsx
**Design-05: Ensure comments are appropriate.**
Line 4 could be more descriptive and relevant to the actual code.
More comments should be used throughout the code.

### Landing.jsx
**Design-05: Ensure comments are appropriate.**
More comments should be used throughout the code.

**Design-08: Ensure code is DRY.**
Each segment block (lines 13, 32, etc.)  has the same style code. 

Not sure what checklist this would fall under, but consider using Semantic UI React's icon element instead of \<i\> in lines 14, 44, etc.

**Comment by alohajerome** [comment]
LandingAddition.jsx:
-Nothing to suggest... Everything looks fine

Landing.jsx:
-Design-05: Ensure that coders without javascript background can understand what you are trying to do.
-Design-08: Reusing the same style code more than 2 times, is considered bad coding. Maybe define a style class that can be used on all columns.

**Comment by saitoshi** [comment]
Landing.jsx
Design 01: Can probably condense to make it easier.
Design 05: Comments so that both Javascript users and non users can understand what or how the code executes
LandingAddition.jsx:
Seems fine.

**Comment by mkirts** [comment]
LandingAddition.jsx:

Design-01: One tab per line from lines 11 through 16
Design-05: Add comments that help explain what the code does
Landing.jsx:

Design-05: Add comments that help explain what the code does
Design-08: Style code is reused twice

**Comment by awongway** [comment]
LandingAddition.jsx:
looks good. 

Landing.jsx:
Design-05: Add comments to help clarity of code. 
Design-08: the style code was used twice
