### ISSUE TITLE
Create the Landing Page

### ISSUE THREAD

**Issue by CalianaFortin** [shocking-development/shockingdevelopment#5]
Please do work for this task in a branch named issue- #05.

- [x]  Make the landing page correspond to the mockup
- 
<img width="647" alt="mockup-landing" src="https://user-images.githubusercontent.com/70739998/106093349-3268e300-60d4-11eb-86ba-22521410f7c8.png">

**Comment by CalianaFortin** [comment]
### **Overview**
For this review, we're going to take a look at the Landing Page.

### **Review Branch**
review-#5

### **Files to review**
Footer.jsx
LandingAddition.jsx
LandingDataAddition.jsx
NavBar2.jsx
Landing.jsx

### **Checklists**

[Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
[Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
[JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)

### **Due date**
Sunday, January 31st

**Comment by CalianaFortin** [comment]
![Screenshot_2021-01-28 meteor-application-template](https://user-images.githubusercontent.com/70739998/106167154-04fe5280-6131-11eb-8cd0-6c8cadfc3b88.png)

**Comment by jtmoka** [comment]
Page: Landing.jsx
Problem: Design Checklist, Design-04
The settings are individually for each of the segment. that repeats the code 4 times.

**Comment by trey-sumida** [comment]
Design-07: Ensure code is readable
Landing.jsx:
Consider putting comments to describe what information each column has

Design-08: Ensure code is DRY
Landing.jsx:
Styling is repeated for multiple components, consider putting it in the css file and giving the components a className

**Comment by kyraikeda** [comment]
### LandingAddition
**Design-05: Ensure comments are appropriate.**
Line 4 could be more descriptive and relevant to the actual code.
More comments should be used throughout the code.

### Landing
**Design-05: Ensure comments are appropriate.**
More comments should be used throughout the code.

**Design-08: Ensure code is DRY.**
Each segment block (lines 13, 32, etc.)  has the same style code. 

Not sure what checklist this would fall under, but consider using Semantic UI React's icon element instead of <i> in lines 14, 44, etc.

**Comment by alohajerome** [comment]
LandingAddition.jsx:
 -Nothing to suggest... Everything looks fine

Landing.jsx:
-Design-05: Ensure that coders without javascript background can understand what you are trying to do.
-Design-08: Reusing the same style code more than 2 times, is considered bad coding. Maybe define a style class that can be used on all columns.

**Comment by saitoshi** [comment]
LandingAddition.jsx 
Design 01: Can probably condense to make it easier. 
Design 05: Comments so that both Javascript users and non users can understand what or how the code executes

**Comment by mkirts** [comment]
LandingAddition.jsx:
- Design-01: One tab per line from lines 11 through 16
- Design-05: Add comments that help explain what the code does

Landing.jsx:
- Design-05: Add comments that help explain what the code does
- Design-08: Style code is reused twice
